// Package scaci implements the MIOTY Service Center Application Center Interface (SCACI) v1.0.0
package scaci

import (
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"sync"
	"time"

	"github.com/Kiloiot/kilo-service-center/KC-DB/storage/models"
	"github.com/Kiloiot/kilo-service-center/pkg/clock"

	"github.com/google/uuid"
)

// SessionState represents the state of a SCACI session handshake
type SessionState string

// SCACI session states per MIOTY SCACI v1.0.0 §3.3
const (
	// StateConnecting indicates session is connecting (before conCmp)
	StateConnecting SessionState = "connecting"
	// StateReissuing indicates a session whose connect operation completed
	// and that is reissuing what it held (SCACI §1, §3.3); SC operations
	// started meanwhile go out after the reissue.
	StateReissuing SessionState = "reissuing"
	// StateActive indicates session is active (after conCmp)
	StateActive SessionState = "active"
)

// Session represents an active SCACI session per MIOTY SCACI v1.0.0 §3.3
//
// Session lifecycle:
//  1. AC initiates connection with Connect (opId=0)
//  2. SC responds with ConnectResponse containing snScUuid
//  3. AC completes with ConnectComplete
//  4. Operations use positive (AC) / negative (SC) opIds
//  5. On reconnect, AC provides snAcUuid to resume
type Session struct {
	// Database ID for persistence
	ID int64 // Database row ID (0 until persisted)

	// Tenant isolation
	TenantID int64

	// Organization isolation (Kilo Cloud integration)
	// Populated from TLS cert CN via orgResolver.ResolveCert or from GetDefaultOrgForTenant
	// Persisted to scaci_sessions.organization_id for multi-tenant isolation
	OrganizationID uuid.UUID

	// Application Center identification
	AcEui uint64 // Application Center EUI64

	// Session UUIDs for resumption per SCACI §3.3
	SnAcUUID UUID16 // AC session UUID (from AC, must match to resume)
	SnScUUID UUID16 // SC session UUID (generated by SC, returned to AC)

	// ops holds the operation IDs of the session (SCACI §3.2).
	ops opLedger

	// Session state
	State     SessionState // Handshake completion tracking
	Resumed   bool         // True if session was resumed from previous connection
	Connected time.Time    // When connection was established
	LastSeen  time.Time    // Last message timestamp (for keepalive monitoring)

	// Protocol version negotiated at connect per SCACI §§2.1-2.3
	// Resume attempts must match this version (major.minor only; patch ignored)
	NegotiatedVersion string // e.g., "1.0.0" - set during handleConnect, persisted in handleConnectComplete

	// Metadata from Connect message per SCACI §3.3.1
	// Stores vendor, model, name, swVersion, and info (arbitrary object)
	Metadata map[string]interface{}

	// stateMu guards what other goroutines touch besides the connection
	// handler - broadcasts, the idle monitor and the reissue: State and
	// LastSeen.
	stateMu sync.Mutex

	// Write synchronization per SCACI §1.6
	WriteMu sync.Mutex // Protects concurrent writes to connection

	// issueMu serializes the SC operations the session issues, so a resume
	// reissues what it holds before any later operation goes out (SCACI §3.2).
	issueMu sync.Mutex
}

// NewSession creates a new SCACI session stamped at now. It fails when the
// platform cannot supply cryptographically secure randomness for the session
// UUID: a predictable session identifier must never be issued.
//
// Parameters:
//   - now: Connect and last-seen time of the new session
//   - tenantID: Tenant identifier for multi-tenant isolation
//   - acEui: Application Center EUI64
//   - snAcUUID: AC session UUID from Connect message
func NewSession(now time.Time, tenantID int64, acEui uint64, snAcUUID UUID16) (*Session, error) {
	snScUUID, err := generateSessionUUID()
	if err != nil {
		return nil, err
	}
	return &Session{
		ID:        0, // Will be set after database persistence
		TenantID:  tenantID,
		AcEui:     acEui,
		SnAcUUID:  snAcUUID,
		SnScUUID:  snScUUID,
		State:     StateConnecting,
		Resumed:   false,
		Connected: now,
		LastSeen:  now,
		Metadata:  make(map[string]interface{}),
	}, nil
}

// EnsureMetadata initializes the Metadata map if nil (defensive guard)
func (s *Session) EnsureMetadata() {
	if s.Metadata == nil {
		s.Metadata = make(map[string]interface{})
	}
}

// currentState reports the session state; the replay moves a resumed session
// on from another goroutine.
func (s *Session) currentState() SessionState {
	s.stateMu.Lock()
	defer s.stateMu.Unlock()
	return s.State
}

// setState moves the session to state.
func (s *Session) setState(state SessionState) {
	s.stateMu.Lock()
	defer s.stateMu.Unlock()
	s.State = state
}

// connected reports whether the session completed its connect operation
// (SCACI §3.3), so SC operations are addressed to its connection.
func (s *Session) connected() bool {
	state := s.currentState()
	return state == StateActive || state == StateReissuing
}

// ApplicationCenter names the Application Center a session belongs to: its
// acEui in one organization of a tenant (SCACI §1). uuid.Nil is the
// organization of the sessions without one.
type ApplicationCenter struct {
	TenantID       int64
	OrganizationID uuid.UUID
	AcEui          uint64
}

// ApplicationCenterOf is the Application Center of acEui in the organization
// orgID of the tenant; a nil organization is the one of sessions without one.
func ApplicationCenterOf(tenantID int64, orgID *uuid.UUID, acEui uint64) ApplicationCenter {
	ac := ApplicationCenter{TenantID: tenantID, AcEui: acEui}
	if orgID != nil {
		ac.OrganizationID = *orgID
	}
	return ac
}

// Key is the Application Center as the session store names it.
func (a ApplicationCenter) Key() models.SCACIApplicationCenter {
	key := models.SCACIApplicationCenter{TenantID: a.TenantID, OrganizationID: a.organization()}
	binary.BigEndian.PutUint64(key.AcEUI[:], a.AcEui)
	return key
}

// organization is the Application Center's organization; nil for a session
// without one, a single-organization tenant's, which reaches the whole tenant.
func (a ApplicationCenter) organization() *uuid.UUID {
	if a.OrganizationID == uuid.Nil {
		return nil
	}
	orgID := a.OrganizationID
	return &orgID
}

// ApplicationCenter is the Application Center the session belongs to.
func (s *Session) ApplicationCenter() ApplicationCenter {
	return ApplicationCenter{TenantID: s.TenantID, OrganizationID: s.OrganizationID, AcEui: s.AcEui}
}

// SupersededBy reports whether next replaces this session: it resumes this
// session, or it is a session of the same Application Center, so another
// organization claiming the acEui replaces nothing.
func (s *Session) SupersededBy(next *Session) bool {
	if s.ID > 0 && s.ID == next.ID {
		return true
	}
	return s.ApplicationCenter() == next.ApplicationCenter()
}

// UpdateLastSeen updates the session's last activity timestamp
func (s *Session) UpdateLastSeen(now time.Time) {
	s.stateMu.Lock()
	defer s.stateMu.Unlock()
	s.LastSeen = now
}

// IdleFor reports how long before now the session last saw activity.
func (s *Session) IdleFor(now time.Time) time.Duration {
	s.stateMu.Lock()
	defer s.stateMu.Unlock()
	return now.Sub(s.LastSeen)
}

// generateSessionUUID generates a random 16-byte session UUID using
// crypto/rand. An entropy failure is returned to the caller; there is no
// predictable fallback.
func generateSessionUUID() (UUID16, error) {
	var uuid UUID16
	if _, err := rand.Read(uuid[:]); err != nil {
		return UUID16{}, fmt.Errorf("%s: %w", ErrSessionEntropyFailure, err)
	}
	return uuid, nil
}

// FormatUUID returns a hex string representation of a UUID
//
// Parameters:
//   - uuid: 16-byte UUID
//
// Returns:
//   - string: Hex-encoded UUID (32 characters)
func FormatUUID(uuid UUID16) string {
	return fmt.Sprintf("%x", uuid)
}

// FormatEUI64 - use mioty.FormatEUI64 from pkg/mioty/format.go
// Removed to maintain single source of truth per centralization mandate

// NewSessionFactory binds the clock every new session is stamped from.
func NewSessionFactory(clk clock.Clock) func(tenantID int64, acEui uint64, snAcUUID UUID16) (*Session, error) {
	return func(tenantID int64, acEui uint64, snAcUUID UUID16) (*Session, error) {
		return NewSession(clk.Now(), tenantID, acEui, snAcUUID)
	}
}
