// Package scaci implements the MIOTY Service Center Application Center Interface (SCACI) v1.0.0
package scaci

import (
	"bytes"
	"crypto/rand"
	"encoding/binary"
	"fmt"
	"sync"
	"time"

	"github.com/google/uuid"
)

// SessionState represents the state of a SCACI session handshake
type SessionState string

// SCACI session states per MIOTY SCACI v1.0.0 §3.3
const (
	// StateConnecting indicates session is connecting (before conCmp)
	StateConnecting SessionState = "connecting"
	// StateActive indicates session is active (after conCmp)
	StateActive SessionState = "active"
	// StateDisconnected indicates connection closed
	StateDisconnected SessionState = "disconnected"
)

// Session represents an active SCACI session per MIOTY SCACI v1.0.0 §3.3
//
// Session lifecycle:
//  1. AC initiates connection with Connect (opId=0)
//  2. SC responds with ConnectResponse containing snScUuid
//  3. AC completes with ConnectComplete
//  4. Operations use positive (AC) / negative (SC) opIds
//  5. On reconnect, AC provides snAcUuid to resume
//
//revive:disable:var-naming AcOpIdMin/ScOpIdMax/AcOpIdCounter/ScOpIdCounter use lowercase 'd' per MIOTY SCACI §3.2
type Session struct {
	// Database ID for persistence
	ID int64 // Database row ID (0 until persisted)

	// Tenant isolation
	TenantID int64

	// Organization isolation (Kilo Cloud integration)
	// Populated from TLS cert CN via orgResolver.ResolveCert or from GetDefaultOrgForTenant
	// Persisted to scaci_sessions.organization_id for multi-tenant isolation
	OrganizationID uuid.UUID

	// Application Center identification
	AcEui uint64 // Application Center EUI64

	// Session UUIDs for resumption per SCACI §3.3
	SnAcUUID UUID16 // AC session UUID (from AC, must match to resume)
	SnScUUID UUID16 // SC session UUID (generated by SC, returned to AC)

	// Operation ID tracking for resumption per SCACI §3.2
	AcOpIdMin int64 // Minimum required known AC opId to resume (from AC)
	ScOpIdMax int64 // Maximum known SC opId to resume (from AC)

	// Operation ID counters per SCACI §3.2
	// First connect uses opId=0, then counters start
	AcOpIdCounter int64 // Positive, strictly incrementing (starts at 1 after connect)
	ScOpIdCounter int64 // Negative, strictly decrementing (starts at -1 after connect)

	// Session state
	State         SessionState // Handshake completion tracking
	Resumed       bool         // True if session was resumed from previous connection
	SyncPersisted bool         // True if session was sync-persisted in handleConnect (skip async create)
	Connected     time.Time    // When connection was established
	LastSeen      time.Time    // Last message timestamp (for keepalive monitoring)

	// Protocol version negotiated at connect per SCACI §§2.1-2.3
	// Resume attempts must match this version (major.minor only; patch ignored)
	NegotiatedVersion string // e.g., "1.0.0" - set during handleConnect, persisted in handleConnectComplete

	// Metadata from Connect message per SCACI §3.3.1
	// Stores vendor, model, name, swVersion, and info (arbitrary object)
	Metadata map[string]interface{}

	// PendingDeregisterOps caches epEui values for in-flight deregister operations per SCACI §3.7
	// Maps opId -> epEui so that handleDeregisterComplete can perform cleanup even if the DB
	// lookup fails or times out. No mutex required: single-goroutine-per-connection model.
	PendingDeregisterOps map[int64]uint64

	// Write synchronization per SCACI §1.6
	WriteMu sync.Mutex // Protects concurrent writes to connection
}

// NewSession creates a new SCACI session
//
// Parameters:
//   - tenantID: Tenant identifier for multi-tenant isolation
//   - acEui: Application Center EUI64
//   - snAcUUID: AC session UUID from Connect message
//
// Returns:
//   - *Session: Initialized session ready for use
func NewSession(tenantID int64, acEui uint64, snAcUUID UUID16) *Session {
	now := time.Now()
	return &Session{
		ID:                   0, // Will be set after database persistence
		TenantID:             tenantID,
		AcEui:                acEui,
		SnAcUUID:             snAcUUID,
		SnScUUID:             generateSessionUUID(),
		AcOpIdCounter:        0, // First AC message after connect will set this
		ScOpIdCounter:        0, // First SC message will decrement to -1
		State:                StateConnecting,
		Resumed:              false,
		Connected:            now,
		LastSeen:             now,
		Metadata:             make(map[string]interface{}),
		PendingDeregisterOps: make(map[int64]uint64),
	}
}

// EnsureMetadata initializes the Metadata map if nil (defensive guard)
func (s *Session) EnsureMetadata() {
	if s.Metadata == nil {
		s.Metadata = make(map[string]interface{})
	}
}

// EnsurePendingDeregisterOps initializes the PendingDeregisterOps map if nil (defensive guard)
// Call this for resumed sessions created via struct literal (sessionFromModel) to ensure
// the cache is ready for deregister operations per SCACI §3.7.
func (s *Session) EnsurePendingDeregisterOps() {
	if s.PendingDeregisterOps == nil {
		s.PendingDeregisterOps = make(map[int64]uint64)
	}
}

// NextAcOpId returns the next Application Center operation ID
//
// Per SCACI §3.2: AC operations use positive, strictly incrementing 64-bit IDs
//
// Returns:
//   - int64: Next positive operation ID
func (s *Session) NextAcOpId() int64 {
	s.AcOpIdCounter++
	return s.AcOpIdCounter
}

// NextScOpId returns the next Service Center operation ID
//
// Per SCACI §3.2: SC operations use negative, strictly decrementing 64-bit IDs
//
// Returns:
//   - int64: Next negative operation ID
func (s *Session) NextScOpId() int64 {
	s.ScOpIdCounter--
	return s.ScOpIdCounter
}

// CanResume determines if a session can be resumed per SCACI §3.3
//
// Resume requirements:
//   - AC session UUID must match previous session
//   - AC opId counter must be consistent
//   - SC opId counter must be consistent
//
// Parameters:
//   - req: Connect message from AC attempting to resume
//
// Returns:
//   - bool: True if session can be resumed
func (s *Session) CanResume(req Connect) bool {
	// UUID must match
	if !bytes.Equal(s.SnAcUUID[:], req.SnAcUUID[:]) {
		return false
	}

	// Check AC opId consistency if provided
	if req.SnAcOpId != nil {
		if *req.SnAcOpId < 0 || *req.SnAcOpId > s.AcOpIdCounter {
			return false // AC opId out of valid range
		}
	}

	// Check SC opId consistency if provided
	if req.SnScOpId != nil {
		if *req.SnScOpId > 0 || *req.SnScOpId < s.ScOpIdCounter {
			return false // SC opId out of valid range
		}
	}

	return true
}

// UpdateLastSeen updates the session's last activity timestamp
func (s *Session) UpdateLastSeen() {
	s.LastSeen = time.Now()
}

// GetAcEuiBytes returns the AC EUI as an 8-byte array (for BYTEA storage)
func (s *Session) GetAcEuiBytes() [8]byte {
	var result [8]byte
	binary.BigEndian.PutUint64(result[:], s.AcEui)
	return result
}

// SetAcEuiFromBytes sets the AC EUI from an 8-byte array (from BYTEA storage)
func (s *Session) SetAcEuiFromBytes(b [8]byte) {
	s.AcEui = binary.BigEndian.Uint64(b[:])
}

// GetSnAcUUIDBytes returns the AC session UUID (for BYTEA storage)
func (s *Session) GetSnAcUUIDBytes() UUID16 {
	return s.SnAcUUID
}

// SetSnAcUUIDFromBytes sets the AC session UUID from bytes (from BYTEA storage)
func (s *Session) SetSnAcUUIDFromBytes(b UUID16) {
	s.SnAcUUID = b
}

// GetSnScUUIDBytes returns the SC session UUID (for BYTEA storage)
func (s *Session) GetSnScUUIDBytes() UUID16 {
	return s.SnScUUID
}

// SetSnScUUIDFromBytes sets the SC session UUID from bytes (from BYTEA storage)
func (s *Session) SetSnScUUIDFromBytes(b UUID16) {
	s.SnScUUID = b
}

// generateSessionUUID generates a random 16-byte session UUID
//
// Uses crypto/rand for cryptographically secure random generation
//
// Returns:
//   - UUID16: Random session UUID
func generateSessionUUID() UUID16 {
	var uuid UUID16
	if _, err := rand.Read(uuid[:]); err != nil {
		// Fallback to timestamp-based UUID if random generation fails
		// This should never happen in practice
		timestamp := time.Now().UnixNano()
		binary.LittleEndian.PutUint64(uuid[0:8], uint64(timestamp))   //nolint:gosec // G115: Safe conversion for UUID generation
		binary.LittleEndian.PutUint64(uuid[8:16], ^uint64(timestamp)) //nolint:gosec // G115: Safe conversion for UUID generation
	}
	return uuid
}

// FormatUUID returns a hex string representation of a UUID
//
// Parameters:
//   - uuid: 16-byte UUID
//
// Returns:
//   - string: Hex-encoded UUID (32 characters)
func FormatUUID(uuid UUID16) string {
	return fmt.Sprintf("%x", uuid)
}

// FormatEUI64 - use mioty.FormatEUI64 from pkg/mioty/format.go
// Removed to maintain single source of truth per centralization mandate

// ParseEUI64 parses a hex string EUI64 to uint64
//
// Accepts:
//   - "1234567890abcdef" (16 hex chars)
//   - "0x1234567890ABCDEF" (with 0x prefix)
//
// Parameters:
//   - s: Hex-encoded EUI64 string
//
// Returns:
//   - uint64: Parsed EUI64 value
//   - error: Parse error if invalid format
func ParseEUI64(s string) (uint64, error) {
	// Remove optional 0x prefix
	if len(s) > 2 && (s[0:2] == "0x" || s[0:2] == "0X") {
		s = s[2:]
	}

	// Validate length (must be exactly 16 hex chars = 8 bytes)
	if len(s) != 16 {
		return 0, fmt.Errorf("EUI64 must be 16 hex characters, got %d", len(s))
	}

	// Parse as uint64 (big-endian)
	var result uint64
	_, err := fmt.Sscanf(s, "%x", &result)
	if err != nil {
		return 0, fmt.Errorf("invalid hex string: %w", err)
	}

	return result, nil
}

// ValidateAcOpId enforces SCACI §3.2: AC uses positive, strictly incrementing IDs
//
// Parameters:
//   - opId: Operation ID to validate
//
// Returns:
//   - error: Validation error if opId is invalid
func (s *Session) ValidateAcOpId(opId int64) error {
	// opId OpIDConnect (0) reserved for Connect handshake only
	if opId == OpIDConnect {
		return fmt.Errorf("opId 0 reserved for connect")
	}

	if opId <= 0 {
		return fmt.Errorf("AC opId must be positive, got %d", opId)
	}

	// First AC message after connect
	if s.AcOpIdCounter == 0 {
		return nil
	}

	if opId <= s.AcOpIdCounter {
		return fmt.Errorf("AC opId must increment (current: %d, got: %d)", s.AcOpIdCounter, opId)
	}

	return nil
}

// UpdateAcOpId records validated AC opId
func (s *Session) UpdateAcOpId(opId int64) {
	if opId > s.AcOpIdCounter && opId > 0 {
		s.AcOpIdCounter = opId
	}
}

// uuidIsZero checks if UUID is all zeros
