package builders

// Error message and format constants for composition-root build failures.
const (
	errFmtCERequiresDefaultOrg                            = "CE requires default org for tenant %d: %w"
	errFmtDeliveryChannelWithoutSender                    = "uplinks are queued for delivery channel %q, which has no sender in this process"
	errFmtFailedToConnectKCIdentity                       = "failed to connect to KC-Identity at %s: %w"
	errFmtFailedToCreateBSSCIServer                       = "failed to create BSSCI server: %w (StatusService is mandatory for pending operation tracking)"
	errFmtFailedToStartBSSCIServer                        = "failed to start mandatory BSSCI server: %w (cannot comply with MIOTY specification without TLS BSSCI endpoint)"
	errFmtSchemaVersionTooOld                             = "schema version too old: current=%d, required=%d"
	errMsgBSSCIConfigurationInvalid                       = "BSSCI configuration invalid"
	errMsgDatabaseConnectionTimeout                       = "database connection timeout"
	errMsgFailedToBuildBSSCIServices                      = "failed to build BSSCI services"
	errMsgFailedToBuildDeliveryWorker                     = "failed to build message delivery worker"
	errMsgFailedToBuildDownlinkExpiryWorker               = "failed to build downlink expiry worker"
	errMsgFailedToBuildRoamingDetector                    = "failed to build roaming detector"
	errMsgFailedToConfigureBSSCIServerRuntime             = "failed to configure BSSCI server runtime"
	errMsgFailedToConnectToMQTTBroker                     = "failed to connect to MQTT broker"
	errMsgFailedToCreateGRPCServer                        = "failed to create gRPC server"
	errMsgFailedToCreateSCACIServer                       = "failed to create SCACI server"
	errMsgRoleSourceNeedsIdentityAddress                  = "identity.address is not set: KC-Core resolves every caller's roles through KC-Identity and cannot authorize a request without it"
	errFmtRoleSourceIdentityClientMissing                 = "identity.address is set (%s) but the infrastructure builder did not connect to KC-Identity: every caller's roles are resolved there"
	errMsgFailedToBuildResumeHolder                       = "failed to build the holder of resumable SCACI sessions"
	errMsgFailedToBuildSessionPersistence                 = "failed to build the SCACI session persistence"
	errMsgFailedToBuildSessionRegistry                    = "failed to build the SCACI session registry"
	errMsgFailedToReconcileSCACISessions                  = "failed to reconcile the SCACI sessions a previous process left live"
	errMsgFailedToInitializeMQTTClient                    = "failed to initialize MQTT client"
	errMsgFailedToInitializeStorage                       = "failed to initialize storage"
	errMsgFailedToBuildKeyMaterialCipher                  = "failed to build key-material cipher from " + envKilocenterMasterKey
	errMsgFailedToRunDatabaseMigrations                   = "failed to run database migrations"
	errMsgFailedToStartSCACIServer                        = "failed to start SCACI server"
	errMsgInvalidConfiguration                            = "invalid configuration"
	errMsgMigrationsRequiredForULPersistence              = "migrations are required for UL persistence; enable_migrations=false"
	errMsgSCACIConfigurationInvalid                       = "SCACI configuration invalid"
	errMsgSCACIEPStatusForwardingEPStatusBroadcasterIsNil = "SCACI EPStatus forwarding: EPStatusBroadcaster is nil"
	errMsgSCACIForwardingBroadcasterIsNil                 = "SCACI forwarding: Broadcaster is nil"
	errMsgSCACIWiringBSSCIServiceBundleIsNil              = "SCACI wiring: BSSCI service bundle is nil"
	errMsgSCACIWiringServerIsNil                          = "SCACI wiring: server is nil"
	errMsgDetachValidationRequiresValidator               = "detach_signature_validation_enabled requires an injected detach signature validator; none ships with this edition"
	errMsgStrictOrgResolutionNilOrgResolver               = "StrictOrgResolution=true but orgResolverSvc is nil - cannot resolve certificates to tenants"
)
