package interfaces

import (
	"context"
	"time"

	"github.com/google/uuid"
)

// CEInstallation holds the identity and federation credentials for a Community Edition instance.
type CEInstallation struct {
	ID                    int        `db:"id"`
	CEID                  uuid.UUID  `db:"ce_id"`
	CompanyName           string     `db:"company_name"`
	OnboardingCompletedAt *time.Time `db:"onboarding_completed_at"`
	FederationToken       *string    `db:"federation_token"`
	TokenIssuedAt         *time.Time `db:"token_issued_at"`
	CreatedAt             time.Time  `db:"created_at"`
	UpdatedAt             time.Time  `db:"updated_at"`
}

// CEInstallationRepository manages the singleton CE installation record.
// It enforces the table's singleton constraint (id = 1).
type CEInstallationRepository interface {
	// Get retrieves the singleton installation record.
	// Returns nil, nil if no record exists yet.
	Get(ctx context.Context) (*CEInstallation, error)

	// Create inserts the initial installation record (CE ID generated by caller).
	Create(ctx context.Context, installation *CEInstallation) error

	// Update applies a partial update using the provided field map.
	// Caller must only include fields that should change.
	Update(ctx context.Context, updates map[string]interface{}) error
}
