-- Add missing Service Center session UUID field to basestation_sessions table
-- This field is required per MIOTY BSSCI v1.0.0 Section 3.3

ALTER TABLE basestation_sessions 
ADD COLUMN IF NOT EXISTS sn_sc_uuid BYTEA;

-- Add comment for clarity
COMMENT ON COLUMN basestation_sessions.sn_sc_uuid IS 'Service Center session UUID (16 bytes) - generated by Service Center per MIOTY BSSCI v1.0.0';