apiVersion: v1
kind: Service
metadata:
  name: {{ include "kilocenter.fullname" . }}-core
  labels:
    {{- include "kilocenter.componentLabels" (dict "context" . "component" "kc-core") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kilocenter.selectorLabels" (dict "context" . "component" "kc-core") | nindent 4 }}
  ports:
    - name: grpc
      port: {{ .Values.kcCore.config.grpc.port }}
      targetPort: grpc
      protocol: TCP
    - name: bssci
      port: {{ .Values.kcCore.config.bssci.port }}
      targetPort: bssci
      protocol: TCP
    - name: scaci
      port: {{ .Values.kcCore.config.scaci.port }}
      targetPort: scaci
      protocol: TCP
    - name: health
      port: {{ .Values.kcCore.config.health.port }}
      targetPort: health
      protocol: TCP
