apiVersion: v1
kind: Service
metadata:
  name: {{ include "kilocenter.fullname" . }}-gateway
  labels:
    {{- include "kilocenter.componentLabels" (dict "context" . "component" "kc-gateway") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kilocenter.selectorLabels" (dict "context" . "component" "kc-gateway") | nindent 4 }}
  ports:
    - name: grpc-web
      port: {{ .Values.kcGateway.config.grpc.port }}
      targetPort: grpc-web
      protocol: TCP
      appProtocol: kubernetes.io/h2c
    - name: health
      port: {{ .Values.kcGateway.config.health.port }}
      targetPort: health
      protocol: TCP
