apiVersion: v1
kind: Service
metadata:
  name: {{ include "kilocenter.fullname" . }}-web
  labels:
    {{- include "kilocenter.componentLabels" (dict "context" . "component" "kc-web") | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "kilocenter.selectorLabels" (dict "context" . "component" "kc-web") | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
