apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kilocenter.fullname" . }}
  labels:
    {{- include "kilocenter.labels" . | nindent 4 }}
type: Opaque
data:
  postgresql-password: {{ .Values.postgresql.password | b64enc | quote }}
  auth-hmac-secret: {{ .Values.secrets.authHmacSecret | b64enc | quote }}
  mqtt-admin-password: {{ .Values.secrets.mqttAdminPassword | b64enc | quote }}
  mqtt-client-password: {{ .Values.secrets.mqttClientPassword | b64enc | quote }}
