import { defineConfig, loadEnv, type ProxyOptions } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';

/**
 * Load version info from release manifest (centralized versioning).
 * Manifest is generated by tools/release/generate_manifest.sh
 */
function loadVersionInfo(): {
  version: string;
  buildTime: string;
  gitCommit: string;
  schemaVersion: number;
  edition: string;
  licenseId: string;
  licenseUrl: string;
  sourceUrl: string;
  docsUrl: string;
  homepageUrl: string;
  trademarkNotice: string;
} {
  const manifestPath = path.resolve(__dirname, '../release/manifest.json');
  try {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
    return {
      version: manifest.version || 'dev-local',
      buildTime: manifest.buildTime || new Date().toISOString(),
      gitCommit: manifest.gitCommit || 'unknown',
      schemaVersion: manifest.schemaVersion || 0,
      edition: manifest.edition ?? 'Community Edition',
      licenseId: manifest.licenseId ?? 'AGPL-3.0-or-later',
      licenseUrl: manifest.licenseUrl ?? 'https://www.gnu.org/licenses/agpl-3.0.html',
      sourceUrl: manifest.sourceUrl ?? 'https://github.com/Kiloiot/kilo-service-center',
      docsUrl: manifest.docsUrl ?? 'https://docs.kiloiot.io/',
      homepageUrl: manifest.homepageUrl ?? 'https://kiloiot.io/mioty-service-center/',
      trademarkNotice:
        manifest.trademarkNotice ?? 'KiloCenter is a trademark of Tim Kravchunovsky.',
    };
  } catch {
    // Fallback for fresh clones before manifest generation
    console.warn('Warning: release/manifest.json not found, using dev defaults');
    return {
      version: 'dev-local',
      buildTime: new Date().toISOString(),
      gitCommit: 'unknown',
      schemaVersion: 0,
      edition: 'Community Edition',
      licenseId: 'AGPL-3.0-or-later',
      licenseUrl: 'https://www.gnu.org/licenses/agpl-3.0.html',
      sourceUrl: 'https://github.com/Kiloiot/kilo-service-center',
      docsUrl: 'https://docs.kiloiot.io/',
      homepageUrl: 'https://kiloiot.io/mioty-service-center/',
      trademarkNotice: 'KiloCenter is a trademark of Tim Kravchunovsky.',
    };
  }
}

/**
 * A gRPC-web stream whose upstream drops mid-response must end for the
 * browser too. The proxy otherwise keeps the browser's response open: the
 * stream never reconnects, and each hung stream holds one of the six
 * connections the browser opens to this host, until module requests of a
 * lazy route wait or fail ("Failed to fetch dynamically imported module").
 */
type ProxyConfigure = NonNullable<ProxyOptions['configure']>;

const endBrowserResponseWithUpstream: ProxyConfigure = (proxy) => {
  proxy.on('proxyRes', (proxyRes, _req, res) => {
    proxyRes.on('close', () => {
      if (!proxyRes.complete) res.destroy();
    });
  });
};

/**
 * A gRPC-web stream counts as open in the browser once its response headers
 * arrive, and a quiet stream sends them before any message. Node would hold a
 * proxied response's headers until its first body bytes, so they are flushed
 * as soon as the proxy starts relaying.
 */
const flushHeadersOnRelay: ProxyConfigure = (proxy) => {
  proxy.on('proxyRes', (_proxyRes, _req, res) => {
    res.once('pipe', () => res.flushHeaders());
  });
};

const grpcWebProxy: ProxyConfigure = (proxy, options) => {
  endBrowserResponseWithUpstream(proxy, options);
  flushHeadersOnRelay(proxy, options);
};

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  loadEnv(mode, process.cwd(), '');
  const versionInfo = loadVersionInfo();

  return {
    plugins: [react()],
    // Generated protobuf files use CommonJS; CJS stubs are copied to
    // node_modules/@kilocenter/grpc-stubs for Vite pre-bundling via grpc:setup.
    optimizeDeps: {
      include: [
        'google-protobuf',
        'google-protobuf/google/protobuf/empty_pb',
        'google-protobuf/google/protobuf/timestamp_pb',
        'google-protobuf/google/protobuf/struct_pb',
        'google-protobuf/google/protobuf/field_mask_pb',
        '@improbable-eng/grpc-web',
        // Linked package for CJS protobuf stubs - Vite pre-bundles these
        '@kilocenter/grpc-stubs/core_pb',
        '@kilocenter/grpc-stubs/core_pb_service',
        '@kilocenter/grpc-stubs/identity_pb',
        '@kilocenter/grpc-stubs/identity_pb_service',
        // Emotion packages - pre-bundle to prevent duplicate instance warning
        '@emotion/react',
        '@emotion/styled',
      ],
      rolldownOptions: {
        transform: {
          define: {
            global: "globalThis",
          },
        },
      },
    },
    // Production build: include generated CJS stubs
    build: {
      commonjsOptions: {
        include: [/node_modules/, /src\/services\/grpc/],
        transformMixedEsModules: true,
      },
      // Suppress chunk size warning for grpc-web + protobuf bundle (cannot be meaningfully split)
      chunkSizeWarningLimit: 1700,
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (
              id.includes('@kilocenter/grpc-stubs') ||
              id.includes('google-protobuf') ||
              id.includes('@improbable-eng/grpc-web')
            )
              return 'vendor-grpc';
            if (id.includes('leaflet') || id.includes('react-leaflet')) return 'vendor-maps';
            if (id.includes('@tanstack/react-query')) return 'vendor-query';
            if (id.includes('@mui/') || id.includes('@emotion/')) return 'vendor-ui';
          },
        },
      },
    },
    // Inject version and disclosure info as compile-time constants
    define: {
      __APP_VERSION__: JSON.stringify(versionInfo.version),
      __BUILD_TIME__: JSON.stringify(versionInfo.buildTime),
      __GIT_COMMIT__: JSON.stringify(versionInfo.gitCommit),
      __SCHEMA_VERSION__: JSON.stringify(versionInfo.schemaVersion),
      __APP_EDITION__: JSON.stringify(versionInfo.edition),
      __LICENSE_ID__: JSON.stringify(versionInfo.licenseId),
      __LICENSE_URL__: JSON.stringify(versionInfo.licenseUrl),
      __SOURCE_URL__: JSON.stringify(versionInfo.sourceUrl),
      __DOCS_URL__: JSON.stringify(versionInfo.docsUrl),
      __HOMEPAGE_URL__: JSON.stringify(versionInfo.homepageUrl),
      __TRADEMARK_NOTICE__: JSON.stringify(versionInfo.trademarkNotice),
    },
    resolve: {
      alias: [
        { find: '@', replacement: path.resolve(__dirname, './src') },
        { find: '@app', replacement: path.resolve(__dirname, './src/app') },
        { find: '@modules', replacement: path.resolve(__dirname, './src/modules') },
        { find: '@components', replacement: path.resolve(__dirname, './src/components') },
        { find: '@ui', replacement: path.resolve(__dirname, './src/ui') },
        { find: '@layouts', replacement: path.resolve(__dirname, './src/layouts') },
        // Generated stubs come from the linked CJS package; every other file under
        // services/grpc (transport, codec, errors, metadata, client) resolves from source.
        {
          find: /^@services\/grpc\/((?:core|identity)_pb(?:_service)?)$/,
          replacement: path.resolve(__dirname, './node_modules/@kilocenter/grpc-stubs/$1'),
        },
        { find: '@services', replacement: path.resolve(__dirname, './src/services') },
        { find: '@contexts', replacement: path.resolve(__dirname, './src/context') },
        { find: '@hooks', replacement: path.resolve(__dirname, './src/hooks') },
        { find: '@utils', replacement: path.resolve(__dirname, './src/utils') },
        { find: '@constants', replacement: path.resolve(__dirname, './src/constants') },
        { find: '@styles', replacement: path.resolve(__dirname, './src/styles') },
        { find: '@router', replacement: path.resolve(__dirname, './src/router') },
        { find: '@api-types', replacement: path.resolve(__dirname, './src/types') },
        { find: '@config', replacement: path.resolve(__dirname, './src/config') },
        { find: '@theme', replacement: path.resolve(__dirname, './src/theme') },
        { find: '@mappers', replacement: path.resolve(__dirname, './src/mappers') },
      ],
    },
    server: {
      allowedHosts: ['.trycloudflare.com'],
      proxy: {
        // gRPC-web proxy to the KC-Gateway ingress
        // Routes all gRPC-web traffic for KiloCenterService, IdentityService, and CoreService
        '^/kilocenter\\.api\\.v1\\.': {
          target: process.env.INGRESS_GRPC_URL || 'http://localhost:9090',
          changeOrigin: true,
          configure: grpcWebProxy,
        },
      },
    },
  };
});
