import { defineConfig, loadEnv } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';
import fs from 'fs';

/**
 * Load version info from release manifest (centralized versioning).
 * Manifest is generated by tools/release/generate_manifest.sh
 */
function loadVersionInfo(): {
  version: string;
  buildTime: string;
  gitCommit: string;
  schemaVersion: number;
  edition: string;
  licenseId: string;
  licenseUrl: string;
  sourceUrl: string;
  docsUrl: string;
  homepageUrl: string;
  trademarkNotice: string;
} {
  const manifestPath = path.resolve(__dirname, '../release/manifest.json');
  try {
    const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf-8'));
    return {
      version: manifest.version || 'dev-local',
      buildTime: manifest.buildTime || new Date().toISOString(),
      gitCommit: manifest.gitCommit || 'unknown',
      schemaVersion: manifest.schemaVersion || 0,
      edition: manifest.edition ?? 'Community Edition',
      licenseId: manifest.licenseId ?? 'AGPL-3.0-or-later',
      licenseUrl: manifest.licenseUrl ?? 'https://www.gnu.org/licenses/agpl-3.0.html',
      sourceUrl: manifest.sourceUrl ?? 'https://github.com/Kiloiot/kilo-service-center',
      docsUrl: manifest.docsUrl ?? 'https://docs.kiloiot.io/',
      homepageUrl: manifest.homepageUrl ?? 'https://kiloiot.io/mioty-service-center/',
      trademarkNotice:
        manifest.trademarkNotice ?? 'KiloCenter is a trademark of Tim Kravchunovsky.',
    };
  } catch {
    // Fallback for fresh clones before manifest generation
    console.warn('Warning: release/manifest.json not found, using dev defaults');
    return {
      version: 'dev-local',
      buildTime: new Date().toISOString(),
      gitCommit: 'unknown',
      schemaVersion: 0,
      edition: 'Community Edition',
      licenseId: 'AGPL-3.0-or-later',
      licenseUrl: 'https://www.gnu.org/licenses/agpl-3.0.html',
      sourceUrl: 'https://github.com/Kiloiot/kilo-service-center',
      docsUrl: 'https://docs.kiloiot.io/',
      homepageUrl: 'https://kiloiot.io/mioty-service-center/',
      trademarkNotice: 'KiloCenter is a trademark of Tim Kravchunovsky.',
    };
  }
}

// https://vite.dev/config/
export default defineConfig(({ mode }) => {
  loadEnv(mode, process.cwd(), '');
  const versionInfo = loadVersionInfo();

  return {
    plugins: [react()],
    // Generated protobuf files use CommonJS; CJS stubs are copied to
    // node_modules/@kilocenter/grpc-stubs for Vite pre-bundling via grpc:setup.
    optimizeDeps: {
      include: [
        'google-protobuf',
        'google-protobuf/google/protobuf/empty_pb',
        'google-protobuf/google/protobuf/timestamp_pb',
        'google-protobuf/google/protobuf/struct_pb',
        'google-protobuf/google/protobuf/field_mask_pb',
        '@improbable-eng/grpc-web',
        // Linked package for CJS protobuf stubs - Vite pre-bundles these
        '@kilocenter/grpc-stubs',
        // Emotion packages - pre-bundle to prevent duplicate instance warning
        '@emotion/react',
        '@emotion/styled',
        '@emotion/cache',
      ],
      rolldownOptions: {
        transform: {
          define: {
            global: "globalThis",
          },
        },
      },
    },
    // Production build: include generated CJS stubs
    build: {
      commonjsOptions: {
        include: [/node_modules/, /src\/services\/grpc/],
        transformMixedEsModules: true,
      },
      // Suppress chunk size warning for grpc-web + protobuf bundle (cannot be meaningfully split)
      chunkSizeWarningLimit: 1700,
      rollupOptions: {
        output: {
          manualChunks(id) {
            if (
              id.includes('@kilocenter/grpc-stubs') ||
              id.includes('google-protobuf') ||
              id.includes('@improbable-eng/grpc-web')
            )
              return 'vendor-grpc';
            if (id.includes('leaflet') || id.includes('react-leaflet')) return 'vendor-maps';
            if (id.includes('recharts')) return 'vendor-charts';
            if (id.includes('@tanstack/react-query')) return 'vendor-query';
            if (id.includes('@mui/') || id.includes('@emotion/')) return 'vendor-ui';
          },
        },
      },
    },
    // Inject version and disclosure info as compile-time constants
    define: {
      __APP_VERSION__: JSON.stringify(versionInfo.version),
      __BUILD_TIME__: JSON.stringify(versionInfo.buildTime),
      __GIT_COMMIT__: JSON.stringify(versionInfo.gitCommit),
      __SCHEMA_VERSION__: JSON.stringify(versionInfo.schemaVersion),
      __APP_EDITION__: JSON.stringify(versionInfo.edition),
      __LICENSE_ID__: JSON.stringify(versionInfo.licenseId),
      __LICENSE_URL__: JSON.stringify(versionInfo.licenseUrl),
      __SOURCE_URL__: JSON.stringify(versionInfo.sourceUrl),
      __DOCS_URL__: JSON.stringify(versionInfo.docsUrl),
      __HOMEPAGE_URL__: JSON.stringify(versionInfo.homepageUrl),
      __TRADEMARK_NOTICE__: JSON.stringify(versionInfo.trademarkNotice),
    },
    resolve: {
      alias: {
        // Path Aliases - Locked Folder Structure per FRONTEND_DELIVERY_PLAN Section 0
        '@': path.resolve(__dirname, './src'),
        '@app': path.resolve(__dirname, './src/app'),
        '@modules': path.resolve(__dirname, './src/modules'),
        '@components': path.resolve(__dirname, './src/components'),
        '@ui': path.resolve(__dirname, './src/ui'),
        '@layouts': path.resolve(__dirname, './src/layouts'),
        // gRPC stubs: linked package for CJS pre-bundling (must be before @services)
        '@services/grpc': path.resolve(__dirname, './node_modules/@kilocenter/grpc-stubs'),
        '@services': path.resolve(__dirname, './src/services'),
        '@contexts': path.resolve(__dirname, './src/context'),
        '@hooks': path.resolve(__dirname, './src/hooks'),
        '@utils': path.resolve(__dirname, './src/utils'),
        '@constants': path.resolve(__dirname, './src/constants'),
        '@styles': path.resolve(__dirname, './src/styles'),
        '@router': path.resolve(__dirname, './src/router'),
        '@api-types': path.resolve(__dirname, './src/types'),
        '@locales': path.resolve(__dirname, './src/locales'),
        '@assets': path.resolve(__dirname, './src/assets'),
        '@config': path.resolve(__dirname, './src/config'),
        '@theme': path.resolve(__dirname, './src/theme'),
        '@mappers': path.resolve(__dirname, './src/mappers'),
      },
    },
    server: {
      allowedHosts: ['.trycloudflare.com'],
      proxy: {
        // gRPC-web proxy to ingress endpoint (KC-Core gRPC-web)
        // Routes all gRPC-web traffic for KiloCenterService, IdentityService, and CoreService
        '^/kilocenter\\.api\\.v1\\.': {
          target: process.env.INGRESS_GRPC_URL || 'http://localhost:9090',
          changeOrigin: true,
        },
      },
    },
  };
});
