// Package bssci provides BSSCI v1.0.0 message metadata registry for normalization.
//
// Implements BSSCI §2.4 requirements for optional field defaults and unknown field tolerance.
//
// This registry defines canonical field specifications for all BSSCI message types:
// - Mandatory fields (must be present and correctly typed)
// - Optional fields (with spec-mandated defaults when absent)
// - Conditional rules (context-dependent field requirements)
//
// References:
// - BSSCI §2.4: Message Interpretation (forward compatibility, optional defaults)
// - BSSCI §3-5: Protocol message specifications
// - MIOTY Radio Protocol §3.6.2: Field type definitions
package bssci

//go:generate go run ../../../../tools/extract_command_directions.go

import (
	"github.com/Kiloiot/kilo-service-center/KC-DB/storage/mioty"
)

// ============================================================================
// Command Direction Types
// ============================================================================

// CommandDirection represents the message flow direction in BSSCI protocol
type CommandDirection string

// Direction constants define message flow per BSSCI three-way handshake pattern
const (
	DirectionBStoSC        CommandDirection = "BS→SC"         // Base Station to Service Center (inbound)
	DirectionSCtoBS        CommandDirection = "SC→BS"         // Service Center to Base Station (outbound)
	DirectionBidirectional CommandDirection = "Bidirectional" // Can be initiated by either party
)

// CommandDirectionMap is auto-generated by tools/extract_command_directions.go
// See message_metadata_directions_gen.go for the complete 56-command mapping
// Used to gate normalization: only BS->SC commands should be normalized per BSSCI §2.4

// ============================================================================
// Field Specification Types
// ============================================================================

// FieldType represents the expected type of a message field
type FieldType string

// Field type constants define the expected Go types for BSSCI message fields
const (
	// TypeInt64 is a signed 64-bit integer field type
	TypeInt64       FieldType = "int64"       // Signed 64-bit integer
	TypeUint64      FieldType = "uint64"      // Unsigned 64-bit integer (EUIs)
	TypeUint32      FieldType = "uint32"      // Unsigned 32-bit integer (counters)
	TypeUint16      FieldType = "uint16"      // Unsigned 16-bit integer (short addresses)
	TypeFloat64     FieldType = "float64"     // 64-bit floating point (SNR, RSSI)
	TypeString      FieldType = "string"      // UTF-8 string
	TypeBool        FieldType = "bool"        // Boolean
	TypeBytes       FieldType = "bytes"       // Byte array (fixed or variable length)
	TypeArray       FieldType = "array"       // Array (numeric or struct)
	TypeStruct      FieldType = "struct"      // Nested structure
	TypeInterface   FieldType = "interface{}" // Any type (config fields)
	TypeGeoLocation FieldType = "geoLocation" // [3]float64 geographic coordinates
	TypeSubpackets  FieldType = "subpackets"  // Subpacket details structure
)

// DL Data Result status values (BSSCI §5.14.1)
const (
	DLDataResultSent    = "sent"    // Downlink successfully sent
	DLDataResultExpired = "expired" // Downlink expired before transmission
	DLDataResultInvalid = "invalid" // Downlink rejected due to validation error
)

// FieldSpec defines the specification for a single message field
type FieldSpec struct {
	Name         string                 // Field name (matches MIOTY spec JSON key)
	Type         FieldType              // Expected field type
	Required     bool                   // Mandatory field (normalization fails if missing)
	DefaultValue interface{}            // Value to substitute when optional field absent
	SpecRef      string                 // BSSCI spec reference (e.g., "§5.8.1 line 234")
	ByteLength   int                    // For byte arrays: expected length (0 = variable)
	Validator    func(interface{}) bool // Custom validation (optional)
}

// ConditionalRule defines context-dependent field requirements
// Example: "responseExp requires dlOpen" (BSSCI §5.11.1)
type ConditionalRule struct {
	Condition func(map[string]interface{}) bool // Evaluates context
	Required  []string                          // Field names that must be present when condition true
	Forbidden []string                          // Field names that must be absent when condition true
	ErrorMsg  string                            // Human-readable error for violations
}

// MessageSpec defines the complete specification for a BSSCI message type
type MessageSpec struct {
	Command          string            // MIOTY command mnemonic (e.g., "statusRsp")
	SpecSection      string            // BSSCI spec section (e.g., "§5.8")
	Direction        CommandDirection  // Protocol direction (BS→SC, SC→BS, or Bidirectional) - Issue #3-4 Fix B1
	MandatoryFields  []FieldSpec       // Fields that must be present
	OptionalFields   []FieldSpec       // Fields that may be absent (with defaults)
	ConditionalRules []ConditionalRule // Context-dependent validation rules
}

// ============================================================================
// Message Registry
// ============================================================================

// messageRegistry maps MIOTY command mnemonics to their message specifications
// Initialized with metadata for all 47 BSSCI message types per v1.0.0 spec
var messageRegistry = map[string]*MessageSpec{
	// ========================================================================
	// Status Operation (§5.8)
	// ========================================================================

	mioty.CmdStatusResponse: {
		Command:     mioty.CmdStatusResponse,
		SpecSection: "§5.8",
		MandatoryFields: []FieldSpec{
			{
				Name:     "code",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.8.1 - POSIX error number (0 = ok)",
			},
			{
				Name:     "message",
				Type:     TypeString,
				Required: true,
				SpecRef:  "§5.8.1 - Status message text",
			},
			{
				Name:     "time",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.8.1 - Unix UTC time (ns resolution)",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "dutyCycle",
				Type:         TypeFloat64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.8.1 - TX duty cycle fraction (sliding 1h window)",
			},
			{
				Name:         "geoLocation",
				Type:         TypeGeoLocation,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.8.1 - Geographic coordinates [lat, lon, alt]",
			},
			{
				Name:         "uptime",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.8.1 - Base station uptime (seconds)",
			},
			{
				Name:         "temp",
				Type:         TypeFloat64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.8.1 - Temperature (°C)",
			},
			{
				Name:         "cpuLoad",
				Type:         TypeFloat64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.8.1 - CPU load normalized to 1.0",
			},
			{
				Name:         "memLoad",
				Type:         TypeFloat64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.8.1 - Memory load normalized to 1.0",
			},
			{
				Name:         "config",
				Type:         TypeInterface,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.8.1 - Configuration object (vendor-specific)",
			},
		},
		ConditionalRules: nil, // No conditional validation for status
	},

	// ========================================================================
	// Attach Operation (§5.6)
	// ========================================================================

	mioty.CmdAttach: {
		Command:     mioty.CmdAttach,
		SpecSection: "§5.6",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.6.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "rxTime",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.6.1 - Unix UTC center of last subpacket (ns)",
			},
			{
				Name:     "attachCnt",
				Type:     TypeUint32,
				Required: true,
				SpecRef:  "§5.6.1 - End Point attachment counter (24-bit)",
				Validator: func(v interface{}) bool {
					// BSSCI §5.6.1: attachCnt is 24-bit unsigned (0 to 16777215)
					val, ok := v.(uint32)
					return ok && val <= 16777215
				},
			},
			{
				Name:     "snr",
				Type:     TypeFloat64,
				Required: true,
				SpecRef:  "§5.6.1 - Signal-to-noise ratio (dB)",
			},
			{
				Name:     "rssi",
				Type:     TypeFloat64,
				Required: true,
				SpecRef:  "§5.6.1 - Signal strength (dBm)",
			},
			{
				Name:       "nonce",
				Type:       TypeBytes,
				Required:   true,
				ByteLength: 4,
				SpecRef:    "§5.6.1 - 4-byte EP nonce",
			},
			{
				Name:       "sign",
				Type:       TypeBytes,
				Required:   true,
				ByteLength: 4,
				SpecRef:    "§5.6.1 - 4-byte EP signature",
			},
			{
				Name:     "dualChan",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.6.1 - Dual channel mode enabled",
			},
			{
				Name:     "repetition",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.6.1 - Repetition enabled",
			},
			{
				Name:     "wideCarrOff",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.6.1 - Wide carrier offset enabled",
			},
			{
				Name:     "longBlkDist",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.6.1 - Long block distance enabled",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "rxDuration",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.6.1 - First to last subpacket center (ns)",
			},
			{
				Name:         "eqSnr",
				Type:         TypeFloat64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent (NOTE: detach defaults this to snr)
				SpecRef:      "§5.6.1 - AWGN equivalent SNR (dB)",
			},
			{
				Name:         "profile",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.6.1 - MIOTY profile (e.g., 'eu1')",
			},
			{
				Name:         "subpackets",
				Type:         TypeSubpackets,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.6.1 - Subpacket SNR/RSSI/frequency/phase arrays",
			},
			{
				Name:         "shAddr",
				Type:         TypeUint16,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.6.1 - EP short address if assigned by BS",
			},
		},
		ConditionalRules: nil, // No conditional validation for attach
	},

	// ========================================================================
	// Detach Operation (§5.7)
	// ========================================================================

	mioty.CmdDetach: {
		Command:     mioty.CmdDetach,
		SpecSection: "§5.7",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.7.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "rxTime",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.7.1 - Unix UTC center of last subpacket (ns)",
			},
			{
				Name:     "packetCnt",
				Type:     TypeUint32,
				Required: true,
				SpecRef:  "§5.7.1 - EP packet counter",
			},
			{
				Name:     "snr",
				Type:     TypeFloat64,
				Required: true,
				SpecRef:  "§5.7.1 - Signal-to-noise ratio (dB)",
			},
			{
				Name:     "rssi",
				Type:     TypeFloat64,
				Required: true,
				SpecRef:  "§5.7.1 - Signal strength (dBm)",
			},
			{
				Name:       "sign",
				Type:       TypeBytes,
				Required:   true,
				ByteLength: 4,
				SpecRef:    "§5.7.1 - 4-byte EP signature",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "rxDuration",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.7.1 - First to last subpacket center (ns)",
			},
			{
				Name:     "eqSnr",
				Type:     TypeFloat64,
				Required: false,
				// NOTE: BSSCI §5.7.1 specifies eqSnr defaults to snr value when absent
				// This is handled by normalizer: if missing, copy from normalized["snr"]
				DefaultValue: nil, // Special case: defaults to snr (applied in normalizer)
				SpecRef:      "§5.7.1 - AWGN equivalent SNR (dB) - defaults to snr when absent",
			},
			{
				Name:         "profile",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.7.1 - MIOTY profile (e.g., 'eu1')",
			},
			{
				Name:         "subpackets",
				Type:         TypeSubpackets,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.7.1 - Subpacket SNR/RSSI/frequency/phase arrays",
			},
		},
		ConditionalRules: nil, // No conditional validation for detach
	},

	// ========================================================================
	// DL Data Result Operation (§5.14)
	// ========================================================================

	mioty.CmdDLDataResult: {
		Command:     mioty.CmdDLDataResult,
		SpecSection: "§5.14",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.14.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "queId",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.14.1 - Queue ID (assigned by SC)",
			},
			{
				Name:     "result",
				Type:     TypeString,
				Required: true,
				SpecRef:  "§5.14.1 - Result status: sent, expired, or invalid",
				Validator: func(v interface{}) bool {
					// Strict enum validation per BSSCI §5.14.1
					result, ok := v.(string)
					if !ok {
						return false
					}
					return result == DLDataResultSent || result == DLDataResultExpired || result == DLDataResultInvalid
				},
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "txTime",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.14.1 - Unix UTC center of first subpacket (ns) - only when result=sent",
			},
			{
				Name:         "packetCnt",
				Type:         TypeUint32,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.14.1 - EP packet counter - only when result=sent",
			},
			{
				Name:         "bsEui",
				Type:         TypeUint64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.14.1 - Base Station EUI64 - only when result=sent",
			},
		},
		ConditionalRules: []ConditionalRule{
			{
				Condition: func(data map[string]interface{}) bool {
					// Rule applies when result="sent"
					result, ok := data["result"].(string)
					return ok && result == DLDataResultSent
				},
				Required:  []string{"txTime", "packetCnt"},
				Forbidden: nil,
				ErrorMsg:  "txTime and packetCnt required when result=sent per BSSCI §5.14.1",
			},
			{
				Condition: func(data map[string]interface{}) bool {
					// Rule applies when result!="sent"
					result, ok := data["result"].(string)
					return ok && result != DLDataResultSent
				},
				Required:  nil,
				Forbidden: []string{"txTime", "packetCnt"},
				ErrorMsg:  "txTime and packetCnt forbidden when result!=sent per BSSCI §5.14.1",
			},
		},
	},

	// ========================================================================
	// UL Data Operation (§5.11)
	// ========================================================================

	mioty.CmdULData: {
		Command:     mioty.CmdULData,
		SpecSection: "§5.11",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.11.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "rxTime",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.11.1 - Unix UTC center of last subpacket (ns)",
			},
			{
				Name:     "packetCnt",
				Type:     TypeUint32,
				Required: true,
				SpecRef:  "§5.11.1 - EP packet counter",
			},
			{
				Name:     "userData",
				Type:     TypeBytes,
				Required: true,
				SpecRef:  "§5.11.1 - User payload data",
			},
			{
				Name:     "snr",
				Type:     TypeFloat64,
				Required: true,
				SpecRef:  "§5.11.1 - Signal-to-noise ratio (dB)",
			},
			{
				Name:     "rssi",
				Type:     TypeFloat64,
				Required: true,
				SpecRef:  "§5.11.1 - Signal strength (dBm)",
			},
			{
				Name:     "dlOpen",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.11.1 - Downlink window opened",
			},
			{
				Name:     "responseExp",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.11.1 - Response expected by EP",
			},
			{
				Name:     "dlAck",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.11.1 - DL acknowledgment flag",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "rxDuration",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.11.1 - First to last subpacket center (ns)",
			},
			{
				Name:         "eqSnr",
				Type:         TypeFloat64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.11.1 - AWGN equivalent SNR (dB)",
			},
			{
				Name:         "profile",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.11.1 - MIOTY profile (e.g., 'eu1')",
			},
			{
				Name:         "mode",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.11.1 - MIOTY mode identifier",
			},
			{
				Name:         "subpackets",
				Type:         TypeSubpackets,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.11.1 - Subpacket SNR/RSSI/frequency/phase arrays",
			},
			{
				Name:         "format",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil, // Pointer type: nil when absent
				SpecRef:      "§5.11.1 - Payload format identifier",
			},
		},
		ConditionalRules: []ConditionalRule{
			{
				Condition: func(data map[string]interface{}) bool {
					// Rule applies when responseExp=true
					responseExp, ok := data["responseExp"].(bool)
					return ok && responseExp
				},
				Required:  []string{"dlOpen"}, // dlOpen field must be present when responseExp=true
				Forbidden: nil,
				ErrorMsg:  "dlOpen required when responseExp=true per MIOTY Radio Protocol §3.6.5.1",
				// Note: Presence check enforced here; value validation (dlOpen==true) in normalizePayload
			},
		},
	},

	// ========================================================================
	// Control Operations (§3)
	// ========================================================================

	mioty.CmdConnect: {
		Command:     mioty.CmdConnect,
		SpecSection: "§3.1",
		MandatoryFields: []FieldSpec{
			{
				Name:     "version",
				Type:     TypeString,
				Required: true,
				SpecRef:  "§3.1.1 - Protocol version major.minor.patch",
			},
			{
				Name:     "bsEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§3.1.1 - Base Station EUI64 (8 bytes)",
			},
			{
				Name:     "bidi",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§3.1.1 - BS bidirectional capability",
			},
			{
				Name:       "snBsUuid",
				Type:       TypeBytes,
				Required:   true,
				ByteLength: 16,
				SpecRef:    "§3.1.1 - BS session UUID (16 bytes)",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "vendor",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§3.1.1 - Vendor name",
			},
			{
				Name:         "model",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§3.1.1 - Model identifier",
			},
			{
				Name:         "name",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§3.1.1 - BS name",
			},
			{
				Name:         "swVersion",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§3.1.1 - Software version",
			},
			{
				Name:         "info",
				Type:         TypeInterface,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§3.1.1 - Arbitrary key-value pairs",
			},
			{
				Name:         "geoLocation",
				Type:         TypeGeoLocation,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§3.1.1 - Geographic coordinates [lat, lon, alt]",
			},
			{
				Name:         "snBsOpId",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§3.1.1 - Minimum required known BS opId to resume",
			},
			{
				Name:         "snScOpId",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§3.1.1 - Maximum known SC opId to resume",
			},
		},
		ConditionalRules: []ConditionalRule{
			{
				// Rule 1: If snBsOpId is present, snScOpId must also be present
				Condition: func(data map[string]interface{}) bool {
					return data["snBsOpId"] != nil
				},
				Required:  []string{"snScOpId"},
				Forbidden: []string{},
				ErrorMsg:  "snScOpId required when snBsOpId present (session resume mutual presence per MIOTY radio spec §3.6.5.3)",
			},
			{
				// Rule 2: If snScOpId is present, snBsOpId must also be present
				Condition: func(data map[string]interface{}) bool {
					return data["snScOpId"] != nil
				},
				Required:  []string{"snBsOpId"},
				Forbidden: []string{},
				ErrorMsg:  "snBsOpId required when snScOpId present (session resume mutual presence per MIOTY radio spec §3.6.5.3)",
			},
		},
	},

	mioty.CmdConnectResponse: {
		Command:          mioty.CmdConnectResponse,
		SpecSection:      "§3.1",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdConnectComplete: {
		Command:          mioty.CmdConnectComplete,
		SpecSection:      "§3.1",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdPing: {
		Command:          mioty.CmdPing,
		SpecSection:      "§3.2",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdPingComplete: {
		Command:          mioty.CmdPingComplete,
		SpecSection:      "§3.2",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdStatus: {
		Command:          mioty.CmdStatus,
		SpecSection:      "§5.8",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdStatusComplete: {
		Command:          mioty.CmdStatusComplete,
		SpecSection:      "§5.8",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	// ========================================================================
	// Attach/Detach Response and Complete (§5.6-5.7)
	// ========================================================================

	mioty.CmdAttachResponse: {
		Command:          mioty.CmdAttachResponse,
		SpecSection:      "§5.6",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdAttachComplete: {
		Command:          mioty.CmdAttachComplete,
		SpecSection:      "§5.6",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDetachResponse: {
		Command:          mioty.CmdDetachResponse,
		SpecSection:      "§5.7",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDetachComplete: {
		Command:          mioty.CmdDetachComplete,
		SpecSection:      "§5.7",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	// ========================================================================
	// Propagate Operations (§5.9-5.10)
	// ========================================================================

	mioty.CmdAttachPropagate: {
		Command:     mioty.CmdAttachPropagate,
		SpecSection: "§5.9",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.9.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "bidi",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.9.1 - Bidirectional capability",
			},
			{
				Name:       "nwkSnKey",
				Type:       TypeBytes,
				Required:   true,
				ByteLength: 16,
				SpecRef:    "§5.9.1 - Network session key (16 bytes)",
			},
			{
				Name:     "shAddr",
				Type:     TypeUint16,
				Required: true,
				SpecRef:  "§5.9.1 - Short address",
			},
			{
				Name:     "lastPacketCnt",
				Type:     TypeUint32,
				Required: true,
				SpecRef:  "§5.9.1 - Last known packet counter",
			},
			{
				Name:     "dualChan",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.9.1 - Dual channel mode",
			},
			{
				Name:     "repetition",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.9.1 - Repetition enabled",
			},
			{
				Name:     "wideCarrOff",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.9.1 - Wide carrier offset",
			},
			{
				Name:     "longBlkDist",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.9.1 - Long block distance",
			},
		},
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdAttachPropagateResponse: {
		Command:          mioty.CmdAttachPropagateResponse,
		SpecSection:      "§5.9",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdAttachPropagateComplete: {
		Command:          mioty.CmdAttachPropagateComplete,
		SpecSection:      "§5.9",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDetachPropagate: {
		Command:     mioty.CmdDetachPropagate,
		SpecSection: "§5.10",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.10.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "shAddr",
				Type:     TypeUint16,
				Required: true,
				SpecRef:  "§5.10.1 - Short address",
			},
		},
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDetachPropagateResponse: {
		Command:          mioty.CmdDetachPropagateResponse,
		SpecSection:      "§5.10",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDetachPropagateComplete: {
		Command:          mioty.CmdDetachPropagateComplete,
		SpecSection:      "§5.10",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	// ========================================================================
	// UL Data Operations (§5.11)
	// ========================================================================

	mioty.CmdULDataResponse: {
		Command:          mioty.CmdULDataResponse,
		SpecSection:      "§5.11",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdULDataComplete: {
		Command:          mioty.CmdULDataComplete,
		SpecSection:      "§5.11",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdULDataTransmit: {
		Command:     mioty.CmdULDataTransmit,
		SpecSection: "§5.11",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.11.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:       "nwkSnKey",
				Type:       TypeBytes,
				Required:   true,
				ByteLength: 16,
				SpecRef:    "§5.11.1 - Network session key (16 bytes)",
			},
			{
				Name:     "shAddr",
				Type:     TypeUint16,
				Required: true,
				SpecRef:  "§5.11.1 - Short address",
			},
			{
				Name:     "packetCnt",
				Type:     TypeUint32,
				Required: true,
				SpecRef:  "§5.11.1 - Packet counter",
			},
			{
				Name:     "userData",
				Type:     TypeBytes,
				Required: true,
				SpecRef:  "§5.11.1 - User payload data",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "profile",
				Type:         TypeString,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.11.1 - MIOTY profile (e.g., 'eu1')",
			},
			{
				Name:         "format",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.11.1 - Payload format identifier",
			},
		},
		ConditionalRules: nil,
	},

	mioty.CmdULDataTransmitResponse: {
		Command:          mioty.CmdULDataTransmitResponse,
		SpecSection:      "§5.11",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdULDataTransmitComplete: {
		Command:          mioty.CmdULDataTransmitComplete,
		SpecSection:      "§5.11",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	// ========================================================================
	// DL Data Operations (§5.12-5.14)
	// ========================================================================

	mioty.CmdDLDataQueue: {
		Command:     mioty.CmdDLDataQueue,
		SpecSection: "§5.12",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.12.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "queId",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.12.1 - Queue ID (assigned by SC)",
			},
			{
				Name:     "userData",
				Type:     TypeBytes,
				Required: true,
				SpecRef:  "§5.12.1 - Downlink payload data",
			},
			{
				Name:     "cntDepend",
				Type:     TypeBool,
				Required: true,
				SpecRef:  "§5.12.1 - Counter dependency flag",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "packetCnt",
				Type:         TypeUint32,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.12.1 - Expected packet counter (when cntDepend=true)",
			},
			{
				Name:         "format",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.12.1 - Payload format identifier",
			},
			{
				Name:         "prio",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.12.1 - Transmission priority",
			},
			{
				Name:         "responseExp",
				Type:         TypeBool,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.12.1 - Response expected flag",
			},
			{
				Name:         "responsePrio",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.12.1 - Response priority",
			},
			{
				Name:         "dlWindReq",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.12.1 - Downlink window request",
			},
			{
				Name:         "expOnly",
				Type:         TypeBool,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.12.1 - Expire-only flag (no transmission)",
			},
		},
		ConditionalRules: nil,
	},

	mioty.CmdDLDataQueueResponse: {
		Command:          mioty.CmdDLDataQueueResponse,
		SpecSection:      "§5.12",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDLDataQueueComplete: {
		Command:          mioty.CmdDLDataQueueComplete,
		SpecSection:      "§5.12",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDLDataRevoke: {
		Command:     mioty.CmdDLDataRevoke,
		SpecSection: "§5.13",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.13.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "queId",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.13.1 - Queue ID to revoke",
			},
		},
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDLDataRevokeResponse: {
		Command:          mioty.CmdDLDataRevokeResponse,
		SpecSection:      "§5.13",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDLDataRevokeComplete: {
		Command:          mioty.CmdDLDataRevokeComplete,
		SpecSection:      "§5.13",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDLDataResultComplete: {
		Command:          mioty.CmdDLDataResultComplete,
		SpecSection:      "§5.14",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	// ========================================================================
	// DL RX Status Operations (§5.15-5.16)
	// ========================================================================

	mioty.CmdDLRxStatus: {
		Command:     mioty.CmdDLRxStatus,
		SpecSection: "§5.15",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.15.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "rxTime",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.15.1 - Unix UTC center of last subpacket (ns)",
			},
			{
				Name:     "packetCnt",
				Type:     TypeUint32,
				Required: true,
				SpecRef:  "§5.15.1 - EP packet counter",
			},
			{
				Name:     "dlRxSnr",
				Type:     TypeFloat64,
				Required: true,
				SpecRef:  "§5.15.1 - EP DL reception SNR (dB)",
			},
			{
				Name:     "dlRxRssi",
				Type:     TypeFloat64,
				Required: true,
				SpecRef:  "§5.15.1 - EP DL reception RSSI (dBm)",
			},
		},
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDLRxStatusComplete: {
		Command:          mioty.CmdDLRxStatusComplete,
		SpecSection:      "§5.15",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDLRxStatusQuery: {
		Command:     mioty.CmdDLRxStatusQuery,
		SpecSection: "§5.16",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.16.1 - End Point EUI64 (8 bytes)",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "startTime",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.16.1 - Query start time (Unix UTC ns)",
			},
			{
				Name:         "endTime",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.16.1 - Query end time (Unix UTC ns)",
			},
			{
				Name:         "limit",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.16.1 - Maximum records to return",
			},
			{
				Name:         "offset",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.16.1 - Pagination offset",
			},
		},
		ConditionalRules: nil,
	},

	mioty.CmdDLRxStatusQueryResponse: {
		Command:          mioty.CmdDLRxStatusQueryResponse,
		SpecSection:      "§5.16",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdDLRxStatusQueryComplete: {
		Command:          mioty.CmdDLRxStatusQueryComplete,
		SpecSection:      "§5.16",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	// ========================================================================
	// Error Handling (§4)
	// ========================================================================

	mioty.CmdError: {
		Command:     mioty.CmdError,
		SpecSection: "§4",
		MandatoryFields: []FieldSpec{
			{
				Name:     "code",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§4.1 - POSIX error number",
			},
			{
				Name:     "message",
				Type:     TypeString,
				Required: true,
				SpecRef:  "§4.1 - Error message text",
			},
		},
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdErrorAck: {
		Command:          mioty.CmdErrorAck,
		SpecSection:      "§4",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	// ========================================================================
	// VM Operations (§5.17-5.20)
	// ========================================================================

	mioty.CmdVMActivate: {
		Command:     mioty.CmdVMActivate,
		SpecSection: "§5.17",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.17.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "macType",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.17.1 - MAC type identifier",
			},
		},
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMActivateResponse: {
		Command:          mioty.CmdVMActivateResponse,
		SpecSection:      "§5.17",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMActivateComplete: {
		Command:          mioty.CmdVMActivateComplete,
		SpecSection:      "§5.17",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMDeactivate: {
		Command:     mioty.CmdVMDeactivate,
		SpecSection: "§5.18",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.18.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "macType",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.18.1 - MAC type identifier",
			},
		},
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMDeactivateResponse: {
		Command:          mioty.CmdVMDeactivateResponse,
		SpecSection:      "§5.18",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMDeactivateComplete: {
		Command:          mioty.CmdVMDeactivateComplete,
		SpecSection:      "§5.18",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMStatus: {
		Command:     mioty.CmdVMStatus,
		SpecSection: "§5.19",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.19.1 - End Point EUI64 (8 bytes)",
			},
		},
		OptionalFields:   nil, // NO macType per vm_handlers.go:930-934
		ConditionalRules: nil,
	},

	mioty.CmdVMStatusResponse: {
		Command:          mioty.CmdVMStatusResponse,
		SpecSection:      "§5.19",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMStatusComplete: {
		Command:          mioty.CmdVMStatusComplete,
		SpecSection:      "§5.19",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMDLData: {
		Command:     mioty.CmdVMDLData,
		SpecSection: "§5.20",
		MandatoryFields: []FieldSpec{
			{
				Name:     "epEui",
				Type:     TypeUint64,
				Required: true,
				SpecRef:  "§5.20.1 - End Point EUI64 (8 bytes)",
			},
			{
				Name:     "macType",
				Type:     TypeInt64,
				Required: true,
				SpecRef:  "§5.20.1 - MAC type identifier",
			},
			{
				Name:     "userData",
				Type:     TypeBytes,
				Required: true,
				SpecRef:  "§5.20.1 - VM downlink payload data",
			},
		},
		OptionalFields: []FieldSpec{
			{
				Name:         "txTime",
				Type:         TypeInt64,
				Required:     false,
				DefaultValue: nil,
				SpecRef:      "§5.20.1 - Scheduled transmission time (Unix UTC ns)",
			},
		},
		ConditionalRules: nil,
	},

	mioty.CmdVMDLDataResponse: {
		Command:          mioty.CmdVMDLDataResponse,
		SpecSection:      "§5.20",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	mioty.CmdVMDLDataComplete: {
		Command:          mioty.CmdVMDLDataComplete,
		SpecSection:      "§5.20",
		MandatoryFields:  nil,
		OptionalFields:   nil,
		ConditionalRules: nil,
	},

	// ========================================================================
	// SC→BS Response Commands (§5.4, §5.10, §5.16)
	// ========================================================================

	mioty.CmdPingResponse: {
		Command:          mioty.CmdPingResponse,
		SpecSection:      "§5.4.3",
		MandatoryFields:  []FieldSpec{},
		OptionalFields:   []FieldSpec{},
		ConditionalRules: []ConditionalRule{},
	},

	mioty.CmdDLDataResultResponse: {
		Command:          mioty.CmdDLDataResultResponse,
		SpecSection:      "§5.10.3",
		MandatoryFields:  []FieldSpec{},
		OptionalFields:   []FieldSpec{},
		ConditionalRules: []ConditionalRule{},
	},

	mioty.CmdDLRxStatusResponse: {
		Command:          mioty.CmdDLRxStatusResponse,
		SpecSection:      "§5.16.3",
		MandatoryFields:  []FieldSpec{},
		OptionalFields:   []FieldSpec{},
		ConditionalRules: []ConditionalRule{},
	},
}

// IsCommandRegistered checks if a BSSCI command has normalization metadata
func IsCommandRegistered(command string) bool {
	_, exists := messageRegistry[command]
	return exists
}

// init populates the Direction field for all MessageSpec entries from CommandDirectionMap.
// This ensures every command has its protocol direction set for normalization gating (Issue #3-4 Fix B1).
func init() {
	for cmd, spec := range messageRegistry {
		if direction, exists := CommandDirectionMap[cmd]; exists {
			spec.Direction = direction
		}
		// Commands not in CommandDirectionMap will have Direction = "" (zero value)
		// which will be treated as "unknown" and default to skipping normalization (safe fallback)
	}
}

// RegisteredCommands returns the list of all commands with normalization metadata
// Useful for automation verification (check all handlers covered)
func RegisteredCommands() []string {
	commands := make([]string, 0, len(messageRegistry))
	for cmd := range messageRegistry {
		commands = append(commands, cmd)
	}
	return commands
}
