// Code generated by tools/extract_command_directions.go. DO NOT EDIT.
// Generated: 2025-12-01 20:58:44

package bssci

import mioty "github.com/Kiloiot/kilo-service-center/KC-DB/storage/mioty"

// CommandDirectionMap maps all 58 BSSCI v1.0.0 commands to their protocol direction
// Derived from KC-DB/storage/mioty/types.go annotations (// Direction: ...)
var CommandDirectionMap = map[string]CommandDirection{
	// Connection operations.
	mioty.CmdConnect:         DirectionBStoSC,
	mioty.CmdConnectResponse: DirectionSCtoBS,
	mioty.CmdConnectComplete: DirectionBStoSC,

	// Ping operations.
	mioty.CmdPing:         DirectionBidirectional,
	mioty.CmdPingResponse: DirectionBStoSC,
	mioty.CmdPingComplete: DirectionBStoSC,

	// Status operations.
	mioty.CmdStatus:         DirectionBidirectional,
	mioty.CmdStatusResponse: DirectionBStoSC,
	mioty.CmdStatusComplete: DirectionBStoSC,

	// Attach operations.
	mioty.CmdAttach:         DirectionBStoSC,
	mioty.CmdAttachResponse: DirectionSCtoBS,
	mioty.CmdAttachComplete: DirectionBStoSC,

	// Detach operations.
	mioty.CmdDetach:         DirectionBStoSC,
	mioty.CmdDetachResponse: DirectionSCtoBS,
	mioty.CmdDetachComplete: DirectionBStoSC,

	// Attach propagate operations.
	mioty.CmdAttachPropagate:         DirectionSCtoBS,
	mioty.CmdAttachPropagateResponse: DirectionBStoSC,
	mioty.CmdAttachPropagateComplete: DirectionBStoSC,

	// Detach propagate operations.
	mioty.CmdDetachPropagate:         DirectionSCtoBS,
	mioty.CmdDetachPropagateResponse: DirectionBStoSC,
	mioty.CmdDetachPropagateComplete: DirectionBStoSC,

	// UL data operations.
	mioty.CmdULData:         DirectionBStoSC,
	mioty.CmdULDataResponse: DirectionSCtoBS,
	mioty.CmdULDataComplete: DirectionBStoSC,

	// UL data transmit operations.
	mioty.CmdULDataTransmit:         DirectionSCtoBS,
	mioty.CmdULDataTransmitResponse: DirectionBStoSC,
	mioty.CmdULDataTransmitComplete: DirectionBStoSC,

	// DL data queue operations.
	mioty.CmdDLDataQueue:         DirectionSCtoBS,
	mioty.CmdDLDataQueueResponse: DirectionBStoSC,
	mioty.CmdDLDataQueueComplete: DirectionBStoSC,

	// DL data revoke operations.
	mioty.CmdDLDataRevoke:         DirectionSCtoBS,
	mioty.CmdDLDataRevokeResponse: DirectionBStoSC,
	mioty.CmdDLDataRevokeComplete: DirectionBStoSC,

	// DL data result operations (BSSCI §3.14). Note: SCACI §3.12 uses different response/complete names.
	mioty.CmdDLDataResult:              DirectionBStoSC,
	mioty.CmdDLDataResultResponse:      DirectionSCtoBS,
	mioty.CmdDLDataResultComplete:      DirectionBStoSC,
	mioty.CmdDLDataResultResponseSCACI: DirectionBStoSC,
	mioty.CmdDLDataResultCompleteSCACI: DirectionSCtoBS,

	// DL RX status operations.
	mioty.CmdDLRxStatus:         DirectionBStoSC,
	mioty.CmdDLRxStatusResponse: DirectionSCtoBS,
	mioty.CmdDLRxStatusComplete: DirectionBStoSC,

	// DL RX status query operations.
	mioty.CmdDLRxStatusQuery:         DirectionSCtoBS,
	mioty.CmdDLRxStatusQueryResponse: DirectionBStoSC,
	mioty.CmdDLRxStatusQueryComplete: DirectionBStoSC,

	// Error operations.
	mioty.CmdError:    DirectionBidirectional,
	mioty.CmdErrorAck: DirectionBidirectional,

	// Variable MAC (VM) sublayer commands (BSSCI Attachment VM v0.4).
	mioty.CmdVMActivate:           DirectionSCtoBS,
	mioty.CmdVMActivateResponse:   DirectionBStoSC,
	mioty.CmdVMActivateComplete:   DirectionBStoSC,
	mioty.CmdVMDeactivate:         DirectionSCtoBS,
	mioty.CmdVMDeactivateResponse: DirectionBStoSC,
	mioty.CmdVMDeactivateComplete: DirectionBStoSC,
	mioty.CmdVMStatus:             DirectionSCtoBS,
	mioty.CmdVMStatusResponse:     DirectionBStoSC,
	mioty.CmdVMStatusComplete:     DirectionBStoSC,
	mioty.CmdVMDLData:             DirectionSCtoBS,
	mioty.CmdVMDLDataResponse:     DirectionBStoSC,
	mioty.CmdVMDLDataComplete:     DirectionBStoSC,
}
